name: PR Security Scan Safe

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Simple Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo message
        run: echo "Workflow is working"
